### ISSUE TITLE
xml.js:   typeof(arg) == 'array'

### ISSUE THREAD

**Issue by mikeTWC1984** [jhuckaby/pixl-webapp#1]
Getting warning from bundler regarding this line

https://github.com/jhuckaby/pixl-webapp/blob/master/js/xml.js#L729

saying that "typeof" operator will never evaluate to "array"

**Comment by jhuckaby** [comment]
Yeah, so this XML parser of mine is *extremely* old.  It was written in 2004 😱, and barely touched since.  Frankly, I am *amazed* it still works.

I expect most bundlers and linters will *hate* this code with a fiery passion.  I can fix the bug you linked to, but... is that the *only* warning your bundler emitted?

It seems like that would be the tip of the iceberg, with JS code that is 18 years old.

🤷🏻‍♂️

**Comment by mikeTWC1984** [comment]
Yeah, it's damn old. But it works though ) No other warning emitted. 
That XML.js file still needed for cronicle UI peace, I think not parser itself but some utility functions (at lease find_object). 
It also referred by cronicle web worker script (that calculates upcoming events), but if I remove it from there it keep working, I guess there is some overlapping functionality with Tools.js

Wondering, are you rewriting that UI engine for orchestra?

**Comment by jhuckaby** [comment]
Bumped deps in Cronicle v0.9.19: https://github.com/jhuckaby/Cronicle/releases/tag/v0.9.19

Yeah, I'm leaving behind pixl-webapp for Orchestra, and have evolved my UI framework.  It's still based on the same core design, but xml.js is out entirely, and I've rewritten and modernized a bunch of it.

I've always resisted frameworks like React, because I feel like I am no longer in control of anything, and can't fix bugs that come up.  I've always preferred to roll my own (with the help of jQuery of course).
